services:
    accounts:
      image: "akmll/accounts:s4"
      container_name: accounts_ms
      ports:
        - 8080:8080
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - akmll

    card:
      image: "akmll/cards:s4"
      container_name: card_ms
      ports:
        - 9000:9000
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - akmll

    loan:
      image: "akmll/loans:s4"
      container_name: loan_ms
      ports:
        - 8090:8090
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - akmll

networks:
  akmll:
    driver: bridge